# Уникальный ключ проекта из вашего сообщения
sonar.projectKey=MBalayan99_DevOps_task_c167ef16-4cfe-4377-ad8c-598edaffb72a

# Имя проекта, которое будет отображаться в интерфейсе
sonar.projectName=DevSeqOps

# Путь к исходному коду (точка означает текущую папку)
sonar.sources=.

# Кодировка исходников
sonar.sourceEncoding=UTF-8
