
sonar.projectKey=MBalayan99_TBot_BTC_USD_39bdb55c-c0bc-41c0-ad95-9c8c07e2adc5


sonar.projectName=TBot_BTC_USD

sonar.sources=.

sonar.language=py
sonar.python.version=3
sonar.sourceEncoding=UTF-8


sonar.exclusions=**/venv/**, **/.pytest_cache/**, **/tests/**
