name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        with:
          args: >
            -Dsonar.projectKey=my_project_key
            -Dsonar.sources=.
            -Dsonar.scanner.skipJreProvisioning=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          # Исправленный синтаксис для заголовка ngrok
          SONAR_SCANNER_OPTS: >-
            -Dhttp.extraHeaders=ngrok-skip-browser-warning:true
